apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budget-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: budget-app
  project: default
  source:
    repoURL: https://github.com/mukeshchaudhary14/Budget-App.git
    targetRevision: HEAD
    path: manifests
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
