development:
  adapter: postgresql
  encoding: unicode
  database: Budgy_development
  pool: 5
  username: Budgy_dp
  password: Azsxdc!#312
  host: db # This should match the service name in your docker-compose.yml

test:
  adapter: postgresql
  encoding: unicode
  database: Budgy_test
  pool: 5
  username: Budgy_ts
  password: Azsxdc!#312
  host: db

production:
  adapter: postgresql
  encoding: unicode
  database: Budgy_production
  pool: 5
  username: Budgy_pr
  password: Azsxdc!#312
  host: db
